# Generated by Django 3.0.6 on 2020-05-17 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='dataset/')),
                ('classification_type', models.CharField(default='binary_crossentropy', max_length=32)),
                ('quantity_class', models.IntegerField(default=0)),
                ('architecture', models.CharField(default='fast_text', max_length=40)),
                ('maxlen', models.BigIntegerField(default=0)),
                ('max_features', models.BigIntegerField(default=5000)),
                ('embedding_dims', models.BigIntegerField(default=128)),
                ('batch_size', models.BigIntegerField(default=32)),
                ('epochs', models.BigIntegerField(default=3)),
                ('format_data', models.CharField(default='', max_length=100)),
                ('train_active', models.BooleanField(default=False)),
                ('file_type', models.CharField(default='txt', max_length=3)),
                ('token_type', models.CharField(default='tokenizer', max_length=10)),
                ('results', models.CharField(default='0', max_length=10)),
            ],
        ),
    ]
