# Generated by Django 3.0.6 on 2020-07-20 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0003_auto_20200523_0727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameters',
            name='architecture',
        ),
        migrations.RemoveField(
            model_name='parameters',
            name='batch_size',
        ),
        migrations.RemoveField(
            model_name='parameters',
            name='borders_class',
        ),
        migrations.RemoveField(
            model_name='parameters',
            name='class_of_later',
        ),
        migrations.RemoveField(
            model_name='parameters',
            name='classification_type',
        ),
        migrations.RemoveField(
            model_name='parameters',
            name='correct_class',
        ),
        migrations.RemoveField(
            model_name='parameters',
            name='embedding_dims',
        ),
        migrations.RemoveField(
            model_name='parameters',
            name='file',
        ),
        migrations.RemoveField(
            model_name='parameters',
            name='file_type',
        ),
        migrations.RemoveField(
            model_name='parameters',
            name='format_data',
        ),
        migrations.RemoveField(
            model_name='parameters',
            name='max_features',
        ),
        migrations.RemoveField(
            model_name='parameters',
            name='maxlen',
        ),
        migrations.RemoveField(
            model_name='parameters',
            name='quantity_class',
        ),
        migrations.RemoveField(
            model_name='parameters',
            name='results',
        ),
        migrations.RemoveField(
            model_name='parameters',
            name='token_type',
        ),
        migrations.RemoveField(
            model_name='parameters',
            name='train_active',
        ),
        migrations.AddField(
            model_name='parameters',
            name='folds',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='parameters',
            name='read',
            field=models.CharField(default='y', max_length=1),
        ),
        migrations.AddField(
            model_name='parameters',
            name='repeats',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='parameters',
            name='train',
            field=models.CharField(default='y', max_length=1),
        ),
        migrations.AddField(
            model_name='parameters',
            name='x_test',
            field=models.FileField(default='1', upload_to='dataset/'),
        ),
        migrations.AddField(
            model_name='parameters',
            name='x_train',
            field=models.FileField(default='1', upload_to='dataset/'),
        ),
        migrations.AddField(
            model_name='parameters',
            name='y_test',
            field=models.FileField(default='1', upload_to='dataset/'),
        ),
        migrations.AddField(
            model_name='parameters',
            name='y_train',
            field=models.FileField(default='1', upload_to='dataset/'),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='epochs',
            field=models.IntegerField(default=10),
        ),
    ]
