# Generated by Django 3.0.6 on 2020-07-20 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0004_auto_20200720_0350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parameters',
            old_name='read',
            new_name='predict',
        ),
    ]
