# Generated by Django 3.0.6 on 2020-07-20 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0005_auto_20200720_0503'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parameters',
            old_name='train',
            new_name='read',
        ),
    ]
