# Generated by Django 3.0.6 on 2020-07-27 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0007_parameters_train'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameters',
            name='process',
            field=models.CharField(default='0', max_length=5),
        ),
    ]
