# Generated by Django 3.0.6 on 2020-07-27 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0008_parameters_process'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameters',
            name='train_active',
            field=models.BooleanField(default=True),
        ),
    ]
