# Generated by Django 3.0.6 on 2020-07-29 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0009_parameters_train_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameters',
            name='hash_name',
            field=models.CharField(default='A', max_length=70),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='process',
            field=models.CharField(default='0.1', max_length=5),
        ),
    ]
