# Generated by Django 3.0.6 on 2020-07-29 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0010_auto_20200729_0552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameters',
            name='process',
        ),
    ]
