# Generated by Django 3.0.6 on 2020-09-26 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0011_remove_parameters_process'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneFot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file1', models.FileField(blank=True, default='1', upload_to='sourceСodes/')),
                ('file2', models.FileField(blank=True, default='1', upload_to='sourceСodes/')),
                ('file3', models.FileField(blank=True, default='1', upload_to='sourceСodes/')),
                ('file4', models.FileField(blank=True, default='1', upload_to='sourceСodes/')),
                ('file5', models.FileField(blank=True, default='1', upload_to='sourceСodes/')),
                ('file6', models.FileField(blank=True, default='1', upload_to='sourceСodes/')),
                ('file7', models.FileField(blank=True, default='1', upload_to='sourceСodes/')),
                ('file8', models.FileField(blank=True, default='1', upload_to='sourceСodes/')),
                ('file9', models.FileField(blank=True, default='1', upload_to='sourceСodes/')),
                ('file10', models.FileField(blank=True, default='1', upload_to='sourceСodes/')),
                ('authors', models.IntegerField(default=5)),
            ],
        ),
    ]
