# Generated by Django 3.0.6 on 2020-09-27 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0012_onefot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onefot',
            name='file1',
        ),
        migrations.RemoveField(
            model_name='onefot',
            name='file10',
        ),
        migrations.RemoveField(
            model_name='onefot',
            name='file2',
        ),
        migrations.RemoveField(
            model_name='onefot',
            name='file3',
        ),
        migrations.RemoveField(
            model_name='onefot',
            name='file4',
        ),
        migrations.RemoveField(
            model_name='onefot',
            name='file5',
        ),
        migrations.RemoveField(
            model_name='onefot',
            name='file6',
        ),
        migrations.RemoveField(
            model_name='onefot',
            name='file7',
        ),
        migrations.RemoveField(
            model_name='onefot',
            name='file8',
        ),
        migrations.RemoveField(
            model_name='onefot',
            name='file9',
        ),
        migrations.AddField(
            model_name='onefot',
            name='zipfile1',
            field=models.FileField(blank=True, default='1', upload_to='sourcecodes/'),
        ),
    ]
