# Generated by Django 3.0.6 on 2020-09-27 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0013_auto_20200927_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onefot',
            name='authors',
        ),
    ]
