# Generated by Django 3.0.6 on 2020-09-27 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0014_remove_onefot_authors'),
    ]

    operations = [
        migrations.AddField(
            model_name='onefot',
            name='number',
            field=models.IntegerField(default=10),
        ),
    ]
