# Generated by Django 3.0.6 on 2021-01-07 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0016_predict'),
    ]

    operations = [
        migrations.AddField(
            model_name='predict',
            name='user_model',
            field=models.FileField(default='none_user_model_11.h5', upload_to='dataset/Models'),
        ),
        migrations.AlterField(
            model_name='predict',
            name='hash_model',
            field=models.CharField(default='none_id_model_11.h5', max_length=255),
        ),
    ]
