# Generated by Django 3.0.6 on 2021-01-07 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0017_auto_20210107_0504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predict',
            name='user_model',
            field=models.FileField(blank=True, default='none_user_model_11.h5', null=True, upload_to='dataset/Models'),
        ),
    ]
