# Generated by Django 3.0.6 on 2021-01-10 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0019_parameters_z_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameters',
            name='folds',
            field=models.IntegerField(default=2),
        ),
    ]
