# Generated by Django 3.0.6 on 2021-01-10 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0020_auto_20210110_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameters',
            name='only_train',
            field=models.CharField(default='n', max_length=1),
        ),
    ]
