# Generated by Django 3.0.6 on 2021-01-14 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0021_parameters_only_train'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameters',
            name='x_test',
        ),
        migrations.RemoveField(
            model_name='parameters',
            name='y_test',
        ),
        migrations.AddField(
            model_name='parameters',
            name='only_zip',
            field=models.CharField(default='n', max_length=1),
        ),
    ]
