# Generated by Django 3.0.6 on 2021-01-14 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0022_auto_20210114_0321'),
    ]

    operations = [
        migrations.AddField(
            model_name='predict',
            name='only_zip',
            field=models.CharField(default='n', max_length=1),
        ),
        migrations.AddField(
            model_name='predict',
            name='zip_file',
            field=models.FileField(default='1', upload_to='dataset/'),
        ),
    ]
