# Generated by Django 3.0.6 on 2021-01-14 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0023_auto_20210114_0624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predict',
            name='zip_file',
            field=models.FileField(default='1', upload_to='dataset/Models'),
        ),
    ]
